In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv("Mobile_data.csv")

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
df.head()

battery_power  clock_speed  fc  int_memory  m_dep  mobile_wt  n_cores  pc  \
0            842          2.2   1           7    0.6        188        2   2   
1           1021          0.5   0          53    0.7        136        3   6   
2            563          0.5   2          41    0.9        145        5   6   
3            615          2.5   0          10    0.8        131        6   9   
4           1821          1.2  13          44    0.6        141        2  14   

   px_height  px_width   ram  sc_h  sc_w  talk_time  price_range  
0         20       756  2549     9     7         19            1  
1        905      1988  2631    17     3          7            2  
2       1263      1716  2603    11     2          9            2  
3       1216      1786  2769    16     8         11            2  
4       1208      1212  1411     8     2         15            1

In [19]:
X=df[['battery_power','clock_speed','int_memory','ram','n_cores','pc','fc']]

In [20]:
y=df['price_range']

In [21]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [22]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [23]:
y_pred=model.predict(X_test)

In [27]:
model.predict([[1600,2.8,40,2600,8,14,0]])

array([2], dtype=int64)

In [28]:
from sklearn.metrics import accuracy_score, confusion_matrix
print("Accuracy:",accuracy_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)

Accuracy: 0.77
[[78 11  0  0]
 [19 67 18  0]
 [ 0 17 67 13]
 [ 0  0 14 96]]
